project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Life is short, learning is long."
  site-url: https://iron-hong.github.io
  favicon: images/site-logo.png
  repo-url: https://iron-hong.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    left: |
      [iron-hong](https://iron-hong.github.io)<br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Blogs"
        href: blog/blog.qmd
      - text: "CV"
        href: CV_en.pdf

format:
  html:
    theme: styles.scss
    toc: true           
    toc-position: right  
    toc-depth: 3         